export const destinations = [
  "Italy",
  "France",
  "Spain",
  "Thailand",
  "Japan",
  "Australia",
  "Mexico",
  "Brazil",
  "United States",
  "Canada",
  "United Kingdom",
  "Greece",
  "Egypt",
  "South Africa",
  "India",
  "China",
  "Indonesia",
  "Peru",
  "New Zealand",
  "Argentina",
  "Morocco",
  "Vietnam",
  "Turkey",
  "Iceland",
  "Croatia",
  "Netherlands",
  "Switzerland",
  "Portugal",
  "Ireland",
  "Sweden",
  "Norway",
  "Germany",
  "Denmark",
  "UAE",
  "Singapore",
  "Malaysia",
  "Philippines",
  "Costa Rica",
  "Colombia",
  "Chile"
];

export const budgetRanges = [
  { value: "budget", label: "Budget ($1000-$3000)" },
  { value: "moderate", label: "Moderate ($3000-$7000)" },
  { value: "luxury", label: "Luxury ($7000+)" }
];
